Repository onboard-github/onboard-aos, pull requests merged in 2024-02, with the labels that each got.

#30 [ONB-172] drawer 게임 플레이 횟수 연동 오류
  data/src/main/java/com/yapp/bol/data/mapper/UserMapper.kt
  data/src/main/java/com/yapp/bol/data/model/user/JoinedGroupDTO.kt
  domain/src/main/java/com/yapp/bol/domain/model/JoinedGroupItem.kt
  presentation/src/main/java/com/yapp/bol/presentation/mapper/HomeMapper.kt
  presentation/src/main/java/com/yapp/bol/presentation/model/DrawerGroupInfoUiModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/utils/Converter.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/UserRankViewModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/group_info/DrawerGroupInfoAdapter.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/group_info/DrawerMyProfileViewHolder.kt
Labels: 🐜 Bug

#33 [ONB-127] 이메일 문의 구현
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/SettingFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/SettingViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ Enhancement

#34 [ONB-157] home profile edit 구현
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/HomeRankFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/group_info/DrawerGroupInfoAdapter.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/home/rank/group_info/DrawerMyProfileViewHolder.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/mypage/MyPageFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/mypage/ProfileSettingActivity.kt
Labels: 🐜 Bug, ✨ Enhancement

#38 메세지 오타 수정 (다식 -> 다시)
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/group/ChangeOwnerFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/group/GroupSettingFragment.kt
Labels: 🐜 Bug

#39 [ONB-52] 회원 탈퇴
  data/src/main/java/com/yapp/bol/data/datasource/user/UserDataSource.kt
  data/src/main/java/com/yapp/bol/data/datasource/user/UserDataSourceImpl.kt
  data/src/main/java/com/yapp/bol/data/mapper/UserMapper.kt
  data/src/main/java/com/yapp/bol/data/model/user/DeleteAccountResponse.kt
  data/src/main/java/com/yapp/bol/data/model/user/JoinedGroupDTO.kt
  data/src/main/java/com/yapp/bol/data/remote/UserApi.kt
  data/src/main/java/com/yapp/bol/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/yapp/bol/domain/model/JoinedGroupItem.kt
  domain/src/main/java/com/yapp/bol/domain/model/core/Role.kt
  domain/src/main/java/com/yapp/bol/domain/model/user/DeleteAccountItem.kt
  domain/src/main/java/com/yapp/bol/domain/repository/UserRepository.kt
  domain/src/main/java/com/yapp/bol/domain/usecase/auth/DeleteAccountUseCase.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/QuitFragment.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/QuitViewModel.kt
  presentation/src/main/java/com/yapp/bol/presentation/view/setting/SettingUiState.kt
  presentation/src/main/res/layout/fragment_quit.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ Enhancement
